### ISSUE TITLE
aquiretoken

### ISSUE THREAD

**Issue by ringodotnl** [jcmontx/angular5-adal-example#1]
Thank you for the example,

Once you add a call to the.service.acquireToken('resourceid') everything in app.component is called twice.
Any idea how to fix that ?

Cheers.

**Comment by QiiLin** [comment]
Same problem here, when I first initiate the page, it goes to the homepage for 1-2s and load itself into the login-in page, after I log-in, the home page gets load twice, there is a clear sign of loading and reloading.

**Comment by jcmontx** [comment]
Sadly this problem is related to the library, this is just an example. You should check the adal-angular5 github.

**Comment by Kelkars** [comment]
I added the below line in my Angular code - main.ts -

if (window === window.parent) {
  platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.log(err));
}

It works for me!
